### ISSUE TITLE
Missing Tournaments from MtgMelee

### ISSUE THREAD

**Issue by uberidiot** [Badaro/MTGODecklistCache#29]
Hello,

I noticed that there are plenty of tournaments from MtgMelee in this repo, but there are many missing. Maybe they were posted retroactively or something?

On the other hand, there is, for example, one listed in Issue #6, [Legacy European Championship Sofia (Pioneer)](https://mtgmelee.com/Tournament/View/12521), that I can't find in this repo. Yet that Issue was closed as completed?

**Comment by Badaro** [comment]
> I noticed that there are plenty of tournaments from MtgMelee in this repo, but there are many missing.

I hand-pick tournaments from MtgMelee to add, usually big ones for Modern/Legacy/Pioneer. Feel free to use the monthly checklist to suggest good ones I may have missed, or even open a separate issue with a list of suggestions.

> On the other hand, there is, for example, one listed in Issue https://github.com/Badaro/MTGODecklistCache/issues/6, [Legacy European Championship Sofia (Pioneer)](https://mtgmelee.com/Tournament/View/12521), that I can't find in this repo. Yet that Issue was closed as completed?

That was a typo on my side when inputting the date for that - it was listed under October instead of November. :) I just pushed a fix moving it to the correct location.

https://github.com/Badaro/MTGODecklistCache/blob/master/Tournaments/mtgmelee.com/2022/11/19/leg-european-championship-sofia-pioneer-2022-11-19.json
