### ISSUE TITLE
Suggested Additional Tournaments from MtgMelee

### ISSUE THREAD

**Issue by uberidiot** [Badaro/MTGODecklistCache#31]
Hello! I got more work for you xD.

Suggested tournaments from MtgMelee since their beginning in 2020 up to today, excluding March 2023.

I retrieved all of them and removed the ones with URI already here. I didn't know your threshold, so I removed all tournaments with less than 10 decks and sorted by number of decks.

Attached as tab-separated plain text for easy automatization.

[mtgmelee_except_march_23.txt](https://github.com/Badaro/MTGODecklistCache/files/11105714/mtgmelee_except_march_23.txt)

EDIT: Forgot to say I only did Modern, Pioneer, Legacy and Pauper.

**Comment by Badaro** [comment]
I'd say the threshold needs to be higher - we're usually comparing to tournaments posting Top 32, so it needs at least a enough players to make this metric relevant. Maybe set a minimum around 50?

Messaged Aliquanto on Discord for an opinion about this since he's the one doing the most analysis with this data.

**Comment by Badaro** [comment]
@uberidiot Is it possible to add a column with the Organizer for each tournament? Would help me in the structure I use.

**Comment by Badaro** [comment]
Some manual review will be needed for this list too. There's a few wierd/mislabeled tournaments, some quick examples:

This is a Team tournament, which can be ingested but requires special handling (that is one of the reasons I haven't fully automated MtgMelee):

```
Legacy	59	2022-03-18	SCG CON Indianapolis - Friday 4:30PM Team Trial	https://mtgmelee.com/Tournament/View/8972
```

This is a tournament in a weird format, not Legacy.

```
Legacy	60	2020-04-18	Constructed Set Roulette	https://mtgmelee.com/Tournament/View/389
```

**Comment by uberidiot** [comment]
Ouch! Manual review it is then...

Organizer column is easy.

Ok, now I have to work, but I'll get to it like, 8 hours from now.

**Comment by Badaro** [comment]
Aliquanto's suggestion is to use 65+ player tournaments (7+rounds) to ensure we're picking up higher-stakes tournaments with more relevant data, which sounds good to me.

That is of course would only be a baseline - we can make exceptions, for instance it we know a particular tournament was highly competitive due to the organizer.

@uberidiot looks good to you? Also means less tournaments to manually review. :D

**Comment by Badaro** [comment]
That is of course would only be a baseline - we can make exceptions, for instance it we know a particular tournament was highly competitive due to the organizer.

**Comment by uberidiot** [comment]
Phew...

That's fine.

Me, I'd get almost everything available, otherwise you are subverting functions. Filtering for "good" data should be a task of the client code. This isn't client code. But it doesn't matter that much in this case and there is some manual part, so it's understandable and fine.

I got the organizers.

Since I'd be filtering by players, I parsed the actual number of (enrolled) players, for accuracy. Turns out the number of decks reported on the search results is barely correct. Plenty of non-team tournaments report more decks than enrolled players. Not inside the tournament page. Inside it's equal or less than the enrolled players.

I filtered out tournaments with 64 or less enrolled players. 45 tournaments survived. I manually reviewed all of them and put notes on like... half of them. Those are the ones likely to get the boot. I didn't see anything weird with the other ones.

I changed the Format column to be a comma-separated list of formats, for the Team tournaments. Those have a note anyway.

I haven't removed any tournament myself. Notes discussion:

- The one with URI https://mtgmelee.com/Tournament/View/8956 is not really a tournament.
- There are more than a dozen with the same note: "3 swiss rounds, few decklists". All of these are the same. Checking one of them is enough to decide on all of them.
- There is a tournament with all rounds being single elimination.
- There is a tournament that was double elimination. Every player with less than two losses keeps playing rounds until only one remains.
- There is a Legacy tournament that permitted playtest cards... but I don't know if they are actually in any desklist.

I forgot that you wanted to keep the possibility of adding some tournament with less than 65 players... The organizer pool is 198 items long. I can post it or something.

I have all the tournaments in a json file, so I can process them again whenever I want.

Attached a tab-separated plain text file with the filtered tournaments, except for March 2023.
[mtgmelee_2023-03_except.txt](https://github.com/Badaro/MTGODecklistCache/files/11116394/mtgmelee_2023-03_except.txt)

EDIT: fixed the attachment by adding back the only tournament from 2023, that I mistakenly moved to March in Issue #28 .

**Comment by Badaro** [comment]
> There are more than a dozen with the same note: "3 swiss rounds, few decklists". All of these are the same. Checking one of them is enough to decide on all of them.

Like this one, right? https://mtgmelee.com/Tournament/View/8956

The scraper doesn't support this type of page (only decklists, no standings or round information), so at least for now we'll have to skip them.

>There is a tournament with all rounds being single elimination.
>There is a tournament that was double elimination. Every player with less than two losses keeps playing rounds until only one remains.

I don't think this matters a lot, but it's good to know.

I'll review the list you sent and ~~write a checklist in a new ticket~~ add them to the repository.

**Comment by Badaro** [comment]
Not parseable at the moment since they use a different page model (no standings/results, only decklists).

- SCG CON Philadelphia - Legacy $10K
- SCG CON Indianapolis - Infinite Challenge Package - *Early Bird Pricing*
- SCG CON Indianapolis - Friday 6:00pm - Modern Challenge+
- SCG CON Indianapolis - Saturday 4:00pm - Modern Challenge
- SCG CON Indianapolis - Saturday 12:30pm - Modern Challenge+
- SCG CON Indianapolis - Saturday 9:00am - Modern Challenge
- SCG CON Indianapolis - Saturday 6:00pm - Modern Challenge
- SCG CON Indianapolis - Sunday 9:00am - Modern Challenge
- SCG CON Indianapolis - Sunday 12:30pm - Modern Challenge+
- SCG CON Dallas - Saturday 4:00pm - Modern Challenge
- SCG CON Dallas - Saturday 12:30pm - Modern Challenge+
- SCG CON Dallas - Saturday 6:00pm - Modern Challenge
- SCG CON Dallas - Saturday 9:00am - Modern Challenge
- SCG CON Dallas - Sunday 9:00am - Modern Challenge
- SCG CON Dallas - Sunday 12:30pm - Modern Challenge+
- Modern Challenge+ - SCG CON Syracuse - Saturday - 6:00 pm
- Modern Challenge+ - SCG CON Baltimore - Saturday - 6:00 pm
- Dreamhack Atlanta 2022 - Fri. Last Chance Qualifier - Pioneer
- Dreamhack Atlanta 2022 - Fri. 1PM Pioneer

A separate issue can be opened to add support to this page format and add these. 

I'm now writing a quick script to generate the control files necessary to add the remaining tournaments.

**Comment by uberidiot** [comment]
Oh. I didn't know there was a difference.

> > There are more than a dozen with the same note: "3 swiss rounds, few decklists". All of these are the same. Checking one of them is enough to decide on all of them.
> 
> Like this one, right? https://mtgmelee.com/Tournament/View/8956

That one has the same structure as the other ones with that note, yeah. But this one specifically, is the one that's not a tournament. It's like a placeholder or something? I left it in just to let you have a say, but just kick it.

I edited the last tab-separated text file to add back the only tournament from 2023, that I mistakenly moved to March in Issue #28 .

**Comment by Badaro** [comment]
> That one has the same structure as the other ones with that note, yeah. But this one specifically, is the one that's not a tournament. It's like a placeholder or something? I left it in just to let you have a say, but just kick it.

To be perfectly honest I never really investigated those pages, no idea what they are meant to be.

Anyway, almost done with the script to add the remaining tournaments (it also detects and skips those in the "not supported" format), will post here when they finish downloading (will probably take a while).

**Comment by Badaro** [comment]
Remaining tournaments from that list uploaded.

@uberidiot feel make more suggestions, even if they don't strictly fit the "65+ players" guideline - but open a new issue for that. This way we can use the issue to track if a specific batch has already been added.

**Comment by Badaro** [comment]
@uberidiot Also, let's make it like this: If you're willing to make the manual review of the tournaments and provide a txt file like the one you provided above I'll add them to the repository - even if it's a 8-player tournament.

However, I won't add those smaller tournaments to my checklist or review them myself since both my time and my interest in MTG is fairly limited nowadays. :)
